//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Properties.AppResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Properties.AppResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string btnAddText {
            get {
                return ResourceManager.GetString("btnAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string btnAllText {
            get {
                return ResourceManager.GetString("btnAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete.
        /// </summary>
        internal static string btnCompleteText {
            get {
                return ResourceManager.GetString("btnCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string btnDeleteText {
            get {
                return ResourceManager.GetString("btnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string btnEditText {
            get {
                return ResourceManager.GetString("btnEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        internal static string btnFTaskNewText {
            get {
                return ResourceManager.GetString("btnFTaskNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string btnOKText {
            get {
                return ResourceManager.GetString("btnOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overdue.
        /// </summary>
        internal static string btnOverdueText {
            get {
                return ResourceManager.GetString("btnOverdueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pending.
        /// </summary>
        internal static string btnPendingText {
            get {
                return ResourceManager.GetString("btnPendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        internal static string btnRefreshText {
            get {
                return ResourceManager.GetString("btnRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string btnSaveText {
            get {
                return ResourceManager.GetString("btnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        internal static string CategoryColumnText {
            get {
                return ResourceManager.GetString("CategoryColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EndDate.
        /// </summary>
        internal static string EndDateColumnText {
            get {
                return ResourceManager.GetString("EndDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add task.
        /// </summary>
        internal static string FormAddTaskText {
            get {
                return ResourceManager.GetString("FormAddTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ToDo List.
        /// </summary>
        internal static string FormAppText {
            get {
                return ResourceManager.GetString("FormAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage Categories.
        /// </summary>
        internal static string FormCategoriesText {
            get {
                return ResourceManager.GetString("FormCategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Category.
        /// </summary>
        internal static string FormCateogoryText {
            get {
                return ResourceManager.GetString("FormCateogoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit task.
        /// </summary>
        internal static string FormEditTaskText {
            get {
                return ResourceManager.GetString("FormEditTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A to-do list is nothing but a list of tasks you need to complete in a certain period of time.
        ///
        ///It’s a very simple, efficient and extremely popular productivity tool.
        ///
        ///HOW TO USE?
        ///On the left there is a calendar for filtering by date, as well as a panel for filtering tasks by status and a button for managing categories; on the top left there are task management buttons: Add, Delete and Edit.
        ///Clicking on the Add or Edit button opens a window for adding or editing a task.To add a new task, you need to fi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string lblDescriptionText {
            get {
                return ResourceManager.GetString("lblDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        internal static string lblFTaskCategoryText {
            get {
                return ResourceManager.GetString("lblFTaskCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string lblFTaskDescriprionText {
            get {
                return ResourceManager.GetString("lblFTaskDescriprionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End date.
        /// </summary>
        internal static string lblFTaskEndDateText {
            get {
                return ResourceManager.GetString("lblFTaskEndDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start date.
        /// </summary>
        internal static string lblFTaskStartDateText {
            get {
                return ResourceManager.GetString("lblFTaskStartDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string lblFTaskTitleText {
            get {
                return ResourceManager.GetString("lblFTaskTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string lblSearchText {
            get {
                return ResourceManager.GetString("lblSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StartText.
        /// </summary>
        internal static string StartDateColumnText {
            get {
                return ResourceManager.GetString("StartDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string StatusColumnText {
            get {
                return ResourceManager.GetString("StatusColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string TitleColumnText {
            get {
                return ResourceManager.GetString("TitleColumnText", resourceCulture);
            }
        }
    }
}
